// <auto-generated />
using System;
using MC.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MC.Repo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220527031848_FixMigration")]
    partial class FixMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MC.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            AddedDate = new DateTime(2022, 5, 27, 10, 18, 48, 114, DateTimeKind.Local).AddTicks(6594),
                            Email = "William",
                            IPAddress = "2",
                            ModifiedDate = new DateTime(2022, 5, 27, 10, 18, 48, 115, DateTimeKind.Local).AddTicks(3200),
                            Password = "Shakespeare",
                            UserName = "duc2"
                        },
                        new
                        {
                            Id = 6L,
                            AddedDate = new DateTime(2022, 5, 27, 10, 18, 48, 115, DateTimeKind.Local).AddTicks(3851),
                            Email = "William",
                            IPAddress = "3",
                            ModifiedDate = new DateTime(2022, 5, 27, 10, 18, 48, 115, DateTimeKind.Local).AddTicks(3856),
                            Password = "Shakespeare",
                            UserName = "duc3"
                        });
                });

            modelBuilder.Entity("MC.Data.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            AddedDate = new DateTime(2022, 5, 27, 10, 18, 48, 116, DateTimeKind.Local).AddTicks(4293),
                            Address = " quang nam",
                            FirstName = " duc",
                            IPAddress = "5",
                            LastName = "vo",
                            ModifiedDate = new DateTime(2022, 5, 27, 10, 18, 48, 116, DateTimeKind.Local).AddTicks(4299)
                        },
                        new
                        {
                            Id = 6L,
                            AddedDate = new DateTime(2022, 5, 27, 10, 18, 48, 116, DateTimeKind.Local).AddTicks(4302),
                            Address = " quang nam",
                            FirstName = " duc",
                            IPAddress = "3",
                            LastName = "vo",
                            ModifiedDate = new DateTime(2022, 5, 27, 10, 18, 48, 116, DateTimeKind.Local).AddTicks(4303)
                        });
                });

            modelBuilder.Entity("MC.Data.UserProfile", b =>
                {
                    b.HasOne("MC.Data.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("MC.Data.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MC.Data.User", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
